### ISSUE TITLE
validation for display name

### ISSUE THREAD

**Issue by nclack** [tlambert03/npe2#22]
This issue proposes a task for adding a validator for `display_name`.

One proposal:
64 character, ascii only, cannot start with space, no tabs

`display_name` is presented in a few different contexts, one of which is the save file dialog.

It appears like the longest plugin name to date is 39 characters long.

**Comment by nclack** [comment]
maybe a 40 character limit is better.

**Comment by neuromusic** [comment]
for reference, our longest plugin name is https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes & its most likely display name would be "Segment Blobs and Things with Membranes" which clocks in at 39 characters

"Allen Cell & Structure Segmenter" hits 32

**Comment by neuromusic** [comment]
even if we set a standard that the napari viewer and the napari hub conform to, both will probably need to do some "cleaning" since we can't guarantee that devs won't go past the stick emoji in there or what have you.

so at best we're promising "follow these naming guidelines and we will accurately name your plugin, otherwise we will coerce tabs to spaces and drop unsupported characters and truncate your plugin's display name"

**Comment by neuromusic** [comment]
comment from @liaprins-czi:

> I think 40 is good! too much beyond that and it is becoming a description instead of a name

**Comment by nclack** [comment]
>  can't guarantee that devs won't go past the length limits or stick emoji in there

With the resolution of this issue, such a manifest would fail to validate and therefore wouldn't load into napari - a warning is issued if a bad manifest is encountered during discovery.

I was hoping to stay out of the cleanup business with this one.

**Comment by neuromusic** [comment]
@nclack ahh, gotcha. I guess we'll still have that risk on the napari hub (since a dev could plausibly release a plugin w/ a bad manifest), but maybe in that case we use the same manifest validation and only support manifest-dependent features if it is a valid manifest
